version: "3.8"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    command: [ "caddy", "reverse-proxy", "--from", "vicap.youngit.org", "--to", "vicap:80" ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  vicap:
    image: antran2202/vicap-weather-service:latest
    platform: "linux/amd64"
    build:
      context: .
    environment:
      ADDRESS: ":80"
      VISUAL_CROSSING_API_KEY: "GAYP28TF9Z3THBSVRE84C6NR3"
      REDIS_HOST: "redis:6379"

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    external: true
  caddy_data:
    external: true
  caddy_config: